### ISSUE TITLE
HTTPS on payment channel logo

### ISSUE THREAD

**Issue by seongliyn** [RazerMS/Shopping-Cart-Plugins-RazerMS_Prestashop#9] opened 2017-07-03 16:31 UTC
I noticed that all payment channel logo are loaded over http instead of HTTPS. Although it will not cause any issue, it will cause the website to show not fully secure.

**Comment by apis17** [comment] 2017-07-04 01:10
Hi seongliyn,
Thank you for your feedback.
May I know which integration you use?

Thanks,

**Comment by seongliyn** [comment] 2017-07-04 03:42
Hi apis17,
I'm using MOLPay PrestaShop Plugin v2.2.9 (it show as v2.2.8 in back office though. I think it is seamless integration.

**Comment by seongliyn** [comment] 2017-07-10 07:33
May I know why this issue is closed? What is the solution?

**Comment by syamimiaziah** [comment] 2017-07-10 07:55
Hi seongliyn. Sorry for closing the issue, I was intended to close other issue.

**Comment by apis17** [comment] 2017-07-10 08:39
Ho seongliyn,
Kindly provide your skype id to support@molpay.com to assist you better.

**Comment by seongliyn** [comment] 2017-07-12 09:44
Hi, it is not really an issue so I'm not sure how you can assist me. As you can see, all the payment logo are loaded over HTTP instead of HTTPS:
![image](https://user-images.githubusercontent.com/29868825/28111889-a31a1c70-6729-11e7-8f8c-af89f9842cad.png)

**Comment by apis17** [comment] 2017-07-12 09:49
Hi seongliyn,
You can rename to https then image will load correctly from https.

**Comment by seongliyn** [comment] 2017-07-12 10:03
Yes. I just want to inform you so that you can change it to HTTPS in next/future release.

**Closed** 2022-04-07 06:16 UTC
